### PR TITLE
Add an Agent META-INF entry matching SpongeMixins to fix detection in…

### PR DESCRIPTION
**Pull request by eigenraven**
… the IDEA plugin.

### CODE REVIEW

**Review by mitchej123 — APPROVED** [review]

**Comment by Glease** [comment]
IDEA plugin relevant code here: https://github.com/minecraft-dev/MinecraftDev/blob/94c0afb6f45245e102ae2b4111ca226d7e5a74a8/src/main/kotlin/platform/mixin/framework/MixinPresentationProvider.kt

though I'm not sure if will work...

**Comment by makamys** [comment]
Did this actually fix the issue for anyone? I did some testing and reached the conclusion that this is actually an issue with RFG and/or GTNH's build script, not GTNHMixins.

### Results

| Repo | Gradle plugin | Mixin loader | Does autocomplete work? |
| --- | --- | --- | --- |
| https://github.com/GTNewHorizons/Hodgepodge/commit/035015166f138ab56c5d5c5acd8d13dad79f95fc | ForgeGradle | GTNHMixins 2.1.3 | Yes |
| https://github.com/GTNewHorizons/Hodgepodge/commit/035015166f138ab56c5d5c5acd8d13dad79f95fc<br><sup>(changed mixin dep)</sup> | ForgeGradle | GTNHMixins 2.1.10 | Yes |
| https://github.com/GTNewHorizons/Hodgepodge/commit/5a6bd17c93cb25b6cbb0693c3775451223cdaa4c | RFG | GTNHMixins 2.1.12 | No |
| https://github.com/GTNewHorizons/Hodgepodge/commit/5a6bd17c93cb25b6cbb0693c3775451223cdaa4c<br><sup>(changed mixin dep)</sup> | RFG | GTNHMixins 2.1.12<br><sup>(added `Implementation-Version`)</sup> | No |
| https://github.com/jss2a98aj/NotFine/commit/2387671fe3ba20e7f9906b6a3d141d03cea9d773<br><sup>(changed mixin dep)</sup> | RFG | upstream Mixin 0.7.11 | No |

By the way, there's something missing in this PR to pass the check in MixinPresentationProvider: `Implementation-Version` has to be set to the Mixin version. However, doing this doesn't fix the issue and only seems to cause the following changes:
* A "cannot resolve target" error will be shown for all target annotations
* The Mixin icon will show up next to GTNHMixins's name in the module libraries window

**Comment by eigenraven** [comment]
Yeah it's not enough, I am still figuring out how to rework the intellij project presentation to be detected by the mcdev plugin correctly

**Comment by Glease** [comment]
Weird thing is the autocompletion works for non vanilla class, e.g. the `@Inject` at https://github.com/GTNewHorizons/Hodgepodge/blob/dde7a7663edc76c8f72cac39038c1fe712be842b/src/main/java/com/mitchej123/hodgepodge/mixins/early/ic2/MixinTileEntityReactorChamberElectricNoDupe.java#L20 has correct auto completion whatever configuration I have, but the early mixins in minecraft package don't have auto completion. This is why I initially thought this was fixed. Perhaps mcdev is failing to detect vanilla classes due to them on a separate configuration?

**Pull request merged**
